name: Windows Installer Tests

on:
  push:
    paths:
      - .github/workflows/*.yml
      - "**Dockerfile"
      - "**.bat"

jobs:
  test_setup_min:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Test setup script
      run: ./setup/choco_min.bat
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: choco_min.bat.log
        path: C:\ProgramData\chocolatey\logs\chocolatey.log

  test_mac_installs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test brew script
      run: |
        chmod 777 ./setup/brew_install.sh
        ./setup/brew_install.sh
    - name: Test brew installs
      run: |
        brew install \
        awscli cask docker terraform
    - name: Test brew installs (upgrade)
      run: |
        brew upgrade \
        azure-cli git python3
    - name: Test cask installs
      run: |
        brew cask install --force \
        anaconda dbeaver-community github google-chrome \
        microsoft-teams r visual-studio-code

  test_setup_full:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Test setup script
      run: ./setup/choco_devops.bat
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: choco_devops.bat.log
        path: C:\ProgramData\chocolatey\logs\chocolatey.log

  print_debug_info:
    runs-on: windows-2019
    steps:
    - name: Print available Windows features
      run: Dism /online /Get-Features
